### ISSUE TITLE
Facts for certificates not being generated

### ISSUE THREAD

**Issue by VendettaMike** [markt-de/puppet-acme#51]
I was reviewing facts on my Puppet server and noticed that only the _acme_csrs_ fact was included, no _acme_certs_ facts. I looked into the _/lib/facter/acme_cert.rb_ code and saw the following: 

```
Dir['/etc/acme.sh/results/*.pem']
  .map { |a| File.basename(a, '.pem') }
  .each do |cert_name|
  crt = File.read("/etc/acme.sh/results/#{cert_name}.pem")
  ca = File.read("/etc/acme.sh/results/#{cert_name}.ca")
```

This looks like it is trying to collect facts from the _results_ directory which is only present on the Puppetserver. On the Puppet node, in my configuration, everything is stored in the _certs_ folder. Changing to the following resulted in the _acme_certs_ facts being created:

````
Dir['/etc/acme.sh/certs/*/*.pem']
  .map { |a| File.basename(File.dirname(a)) }
  .each do |cert_name|
  crt = File.read("/etc/acme.sh/certs/#{cert_name}/cert.pem")
  ca = File.read("/etc/acme.sh/certs/#{cert_name}/chain.pem")`
````

Is this a bug or is it just my configuration?
````
 acme:
    accounts:
    - myemail@mynet.com
    ca_whitelist:
    - letsencrypt
    - letsencrypt_test
    certificates:
      myhost.mynet.com:
        use_profile: nsupdate
        use_account: myemail@mynet.com
        ca: letsencrypt
        notify: Service[myservice]
    default_account: myemail@mynet.com
    default_ca: letsencrypt
    default_profile: nsupdate
    dnssleep: 15
    exec_timeout: 600
    profiles:
      nsupdate:
        challengetype: dns-01
        hook: nsupdate
        env:
          NSUPDATE_SERVER: 10.10.10.10
        options:
          dnssleep: 15
          nsupdate_id: keyname
          nsupdate_type: hmac-sha256
          nsupdate_key: abcdef1234567890
````
