### ISSUE TITLE
Puppet run on Puppet server not picking up acme_csrs from clients

### ISSUE THREAD

**Issue by m0kuj1n** [markt-de/puppet-acme#58]
Hi,
I'm in the process of setting this module up and have deployed the relevant code on both my PuppetCA server:

```
Class { 'acme':
      accounts        => ['email@account'],
      ca_whitelist    => ['letsencrypt','letsencrypt_test'],
      default_account => 'email@account',
      default_ca      => 'letsencrypt',
      default_profile => 'nsupdate',
      profiles        => {
        nsupdate => {
          challengetype => 'dns-01',
          hook          => 'nsupdate',
          env           => {
            'NSUPDATE_SERVER' => 'my.dns.server',
            'NSUPDATE_ZONE'   => 'dns.dyn.zone',
          },
          options       => {
            challenge_alias => 'letsencrypt.dns.dyn.zone',
            dnssleep        => 15,
            nsupdate_id     => le-dyn.zone',
            nsupdate_type   => 'hmac-sha512',
            nsupdate_key    => $nsupdate_key,
          }
        }
      }
    }
```

And on a Test client (in same environment as PuppetCA):

```
  acme::certificate { "${vhost_fqdn}":
    use_profile => 'nsupdate',
    use_account => 'email@account',
    ca          => 'letsencrypt',
    notify      => Class['apache::service'],
  }

  include acme
  $base_dir = $acme::base_dir
  $crt_dir  = $acme::crt_dir
  $key_dir  = $acme::key_dir

  $my_key = "${key_dir}/${vhost_fqdn}/private.key"
  $my_cert = "${crt_dir}/${vhost_fqdn}/cert.pem"
  $my_chain = "${crt_dir}/${vhost_fqdn}/chain.pem"
```

This results in acme.sh being installed on both client and server. On the client a CSR is generated via Puppet:

```
Notice: /Stage[main]/Profile::Client/Acme::Certificate[vhost_fqdn]/Acme::Csr[vhost_fqdn]/Ssl_pkey[/etc/acme.sh/keys/vhost_fqdn/private.key]/ensure: created (corrective)
Notice: /Stage[main]/Profile::Client/Acme::Certificate[vhost_fqdn]/Acme::Csr[vhost_fqdn]/X509_request[/etc/acme.sh/certs/vhost_fqdn/cert.csr]/ensure: created (corrective)
Notice: /Stage[main]/Profile::Client/Acme::Certificate[vhost_fqdn]/Acme::Csr[vhost_fqdn]/File[/etc/acme.sh/keys/vhost_fqdn/private.key]/group: group changed 'root' to 'acme' (corrective)
Notice: /Stage[main]/Profile::Client/Acme::Certificate[vhost_fqdn]/Acme::Csr[vhost_fqdn]/File[/etc/acme.sh/keys/vhost_fqdn/private.key]/mode: mode changed '0644' to '0640' (corrective)
Notice: /Stage[main]/Profile::Client/Acme::Certificate[vhost_fqdn]/Acme::Csr[vhost_fqdn]/File[/etc/acme.sh/keys/vhost_fqdn/private.key]/seluser: seluser changed 'unconfined_u' to 'system_u' (corrective) 
Notice: /Stage[main]/Profile::Client/Acme::Certificate[vhost_fqdn]/Acme::Csr[vhost_fqdn]/File[/etc/acme.sh/certs/vhost_fqdn/cert.csr]/group: group changed 'root' to 'acme' (corrective)
Notice: /Stage[main]/Profile::Client/Acme::Certificate[vhost_fqdn]/Acme::Csr[vhost_fqdn]/File[/etc/acme.sh/certs/vhost_fqdn/cert.csr]/seluser: seluser changed 'unconfined_u' to 'system_u' (corrective) 
Notice: no CSR from facter for cert vhost_fqdn (normal on first run)
Notice: /Stage[main]/Profile::Client/Acme::Certificate[vhost_fqdn]/Acme::Csr[vhost_fqdn]/Notify[no CSR from facter for cert vhost_fqdn (normal on first run)]/message: defined 'message' as 'no CSR from facter for cert vhost_fqdn (normal on first run)'
Info: Acme::Certificate[vhost_fqdn]: Scheduling refresh of Class[Apache::Service]
Info: Class[Apache::Service]: Scheduling refresh of Service[httpd]
Notice: /Stage[main]/Apache::Service/Service[httpd]: Triggered 'refresh' from 1 event
Notice: Applied catalog in 6.76 seconds
```

And this is visible in facter and on Puppetboard:

```
facter -p acme_csrs
{
  vhost_fqdn => "-----BEGIN CERTIFICATE REQUEST-----\nBUNCHOFBASE64=\n-----END CERTIFICATE REQUEST-----\n"
}
```

However it doesn't get picked up by the PuppetCA despite multiple puppet agent runs on both the client and the CA

```
Notice: got no acme_certs from facter (may need another puppet run)
Notice: /Stage[main]/Acme/Notify[got no acme_certs from facter (may need another puppet run)]/message: defined 'message' as 'got no acme_certs from facter (may need another puppet run)'
Notice: Applied catalog in 11.53 seconds
```

Is there an error in my config or something missing? I should also confirm that I have the following in the puppet.conf on my PuppetCA server:

```
trusted_node_data = true
storeconfigs_backend = puppetdb
storeconfigs = true
reports = puppetdb
```

**Comment by m0kuj1n** [comment]
I've done a bit of investigation and I think this issue is actually a result of our architecture. We have a PuppetCA server (not in pool) and 2 compilers and the ACME code was deployed to the PuppetCA role. As the Puppet Agent runs on the 2 pool compilers and not the CA the ACME signing never completes. However as all 3 are speaking to the same PuppetDB is it expected that you need to do the Agent runs for both the client and the ACME server against the same compiler?
If so, is it safe to deploy the ACME code to all 3 compilers or will that result in duplicate cert signings and other issues?

Finally the challenge-alias directive appears to be hard-coded on the ACME server side. As we have a many - many CNAME setup at present (i.e. we have acme_challenge.client.f.q.d.n CNAME _acme_challenge.client.f.q.d.n-devolved.dns-zone) it might be useful to be able to define this at the client side.

**Comment by fraenki** [comment]
> However as all 3 are speaking to the same PuppetDB is it expected that you need to do the Agent runs for both the client and the ACME server against the same compiler? If so, is it safe to deploy the ACME code to all 3 compilers or will that result in duplicate cert signings and other issues?

I don't know how this should be configured. Maybe you just need to change `$acme_host`?
See https://github.com/markt-de/puppet-acme/blob/main/data/common.yaml#L40

> Finally the challenge-alias directive appears to be hard-coded on the ACME server side

It's not hard-coded?
See https://github.com/markt-de/puppet-acme?tab=readme-ov-file#dns-alias-mode

**Comment by m0kuj1n** [comment]
Thanks for getting back to me! The good news is that setting the $acme_host variable solves the issue about the code running on the PuppetCA server (I thought I'd already set it but it turns out I'd only done it on our test environment which was working and has a single Puppet server/CA host).
RE: the challenge-alias my reading of the documentation is that it's defined server-side on a per-profile basis rather than on a per-certificate/client basis? Does the module work with Hiera? I'd tried a Hiera config along the lines of that in https://github.com/markt-de/puppet-acme/issues/51 but it failed to compile saying it couldn't find the profile:

```yaml
acme:
    accounts:
    - 'email@account' 
    ca_whitelist:
    - 'letsencrypt'
    - 'letsencrypt_test'
    default_account: 'email@account'
    default_ca: 'letsencrypt'
    default_profile: 'nsupdate'
    dnssleep: 15
    exec_timeout: 600
   profiles:
      nsupdate:
        challengetype: dns-01
        hook: nsupdate
        challengetype: 'dns-01'
        hook: 'nsupdate'
        env:
          NSUPDATE_SERVER: 'my.dns.server'
          NSUPDATE_ZONE: 'my.dns-dyn.zone'   
        options:
          challenge-alias: 'my.dns-dyn.zone'
          dnssleep: 15
          nsupdate_id: 'dns-dyn.zone'
          nsupdate_type: 'hmac-sha512'
          nsupdate_key: ENC[PKCS7.....
```

**Comment by m0kuj1n** [comment]
So the following YAML layout does work:
```yaml
acme::acme_host: 'puppetca.server'
acme::accounts:
  - 'email@account'
acme::ca_whitelist:
  - 'letsencrypt'
  - 'letsencrypt_test'
acme::default_account: 'email@account'
acme::default_ca: 'letsencrypt'
acme::default_profile: 'nsupdate'
acme::profiles:
  nsupdate:
    challengetype: 'dns-01'
    hook: 'nsupdate'
    env:
      NSUPDATE_SERVER: 'my.dns.server'
      NSUPDATE_ZONE: 'my.dns-dyn.zone'
    options:
      challenge_alias: 'my.dns-dyn.zone'
      dnssleep: 15
      nsupdate_id: 'dns-dyn.zone'
      nsupdate_type: 'hmac-sha512'
      nsupdate_key: "%{lookup('acme_nsupdate_key')}"
```

 So I've figured out 1. Why the exported resources from the client weren't being realised on the Puppet ACME server. 2. How to configure the module using Hiera. This leaves the issue of a single challenge-alias defined on the ACME server, while being to define this on a per-certificate basis on the client-side would be preferable which is now more of a separate feature request/enhancement IMO. Happy to close this issue. Do you want me to submit a separate feature/enhancement request?
